### ISSUE TITLE
After Wire.requestFrom() there is no need to wait and no need for endTransmission.

### ISSUE THREAD

**Issue by Koepel** [pololu/lps-arduino#2]
In the function readReg(), there is a Wire.endTransmission() after the Wire.requestFrom(). That should not be there. The Wire.endTransmission() is only used when writing data.

In the functions readPressureRaw() and readTemperatureRaw() there is a while-loop to wait for data. That waiting is not needed, since all the received I2C data is already in the receive buffer inside the Wire library.
In case there was a bus error, and Wire.available() would return zero bytes, then that loop will halt the code.

**Comment by kevin-pololu** [comment]
Fixed in 3.0.1; thanks.
